name: SBenv
channels:
  - conda-forge
  - defaults
  - pytorch 
  - torchvision 
  - torchaudio
dependencies:
  - python=3.11
  - pytorch=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.6.1
  - xgboost
  - biopython
  - pandas
  - dssp
  - ipykernel
  - matplotlib
  - seaborn
  - pyarrow
  - jinja2
