name: SBenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - biopython
  - pandas
  - dssp
  - ipykernel
  - scikit-learn
  - matplotlib
  - seaborn
  - pyarrow
  - jinja2
  - xgboost