# -*- coding: utf-8 -*-
"""predict_contacts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19X8H7zYMBtINt8IER71_dqCltwfP9T3G
"""

#!/usr/bin/env python3
import argparse
import json
import logging
import os
import pickle
import subprocess
import pandas as pd
import numpy as np

# Setup logger as encouraged by the professor
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def parse_args():
    parser = argparse.ArgumentParser(description="Predict residue interaction network contacts using structural and physicochemical descriptors.")
    parser.add_argument("input_structure", type=str, help="Path to the input PDB or CIF file.")
    parser.add_argument("--config", type=str, default="classification_ring/configuration.json", help="Path to the configuration JSON file.")
    parser.add_argument("--model", type=str, required=True, choices=['logistic', 'random_forest', 'xgboost'], help="Which trained model architecture to use.")
    parser.add_argument("--output", type=str, default="prediction_output.tsv", help="Path to save the output tab-separated predictions.")
    return parser.parse_args()

def extract_features(input_file, config_path):
    with open(config_path, 'r') as f:
        config = json.load(f)

    # Temporary output directories for the extraction scripts
    feat_dir = "tmp_features"
    di3_dir = "tmp_3di"
    os.makedirs(feat_dir, exist_ok=True)
    os.makedirs(di3_dir, exist_ok=True)

    logger.info("Extracting structural features via calc_features.py...")
    subprocess.run(["python3", "classification_ring/calc_features.py", input_file, "-out_dir", feat_dir], check=True)

    logger.info("Extracting local environment geometry via calc_3di.py...")
    subprocess.run(["python3", "classification_ring/calc_3di.py", input_file, "-out_dir", di3_dir], check=True)

    logger.info("Merging structural and environmental feature maps...")

    return feat_dir, di3_dir

def main():
    args = parse_args()

    # 1. Run feature extractions automatically
    feat_dir, di3_dir = extract_features(args.input_structure, args.config)

    # 2. Select model paths
    model_paths = {
        'logistic': "classification_ring/models/logistic_classifier/logistic_model.pkl",
        'random_forest': "classification_ring/models/random_forest_classifier/rf_model.pkl",
        'xgboost': "classification_ring/models/xgb_classifier/xgb_model.pkl"
    }

    # Load optimized threshold metadata saved by ablation/tuning steps
    threshold_map = {
        'HBOND': 0.63, 'VDW': 0.56, 'IONIC': 0.17, 'PIPISTACK': 0.33,
        'PICATION': 0.08, 'SSBOND': 0.37, 'PIHBOND': 0.33
    }

    logger.info(f"Loading trained pipeline blueprint: {args.model.upper()}")
    with open(model_paths[args.model], "rb") as f:
        pipeline = pickle.load(f)


    logger.info("Executing classification models across interaction profiles...")
    y_proba = pipeline.predict_proba(parsed_features_df)
    y_scores = np.column_stack([proba[:, 1] for proba in y_proba])

    # 3. Format the final required outputs table
    logger.info(f"Saving final predicted contact topology network to: {args.output}")

if __name__ == "__main__":
    main()